### ISSUE TITLE
AttributeError: 'MigrationContext' object has no attribute '_update_current_rev'

### ISSUE THREAD

**Issue by techman83** [g2p/bedup#55]
Just noted the following on a fresh install.

```bash
# bedup show
Traceback (most recent call last):
  File "/usr/local/bin/bedup", line 9, in <module>
    load_entry_point('bedup==0.9.0', 'console_scripts', 'bedup')()
  File "/root/.local/lib/python2.7/site-packages/bedup-0.9.0-py2.7-linux-x86_64.egg/bedup/__main__.py", line 487, in script_main
    sys.exit(main(sys.argv))
  File "/root/.local/lib/python2.7/site-packages/bedup-0.9.0-py2.7-linux-x86_64.egg/bedup/__main__.py", line 476, in main
    return args.action(args)
  File "/root/.local/lib/python2.7/site-packages/bedup-0.9.0-py2.7-linux-x86_64.egg/bedup/__main__.py", line 72, in cmd_show_vols
    sess = get_session(args)
  File "/root/.local/lib/python2.7/site-packages/bedup-0.9.0-py2.7-linux-x86_64.egg/bedup/__main__.py", line 102, in get_session
    upgrade_schema(engine)
  File "/root/.local/lib/python2.7/site-packages/bedup-0.9.0-py2.7-linux-x86_64.egg/bedup/migrations.py", line 52, in upgrade_schema
    context._update_current_rev(current_rev, REV)
AttributeError: 'MigrationContext' object has no attribute '_update_current_rev'
```

That method doesn't appear to exist in the MigrationContext class from alembic anymore. Commenting out line 52 does make things run correctly. Figured that was relatively safe on a fresh install (presumably nothing to migrate in the bedup schema if it doesn't exist!).

**Comment by nealmcb** [comment]
Thanks, pcdummy - that worked for me!

The method `_update_current_rev()` seems to have been removed from alembic with this commit, and the move from alembic 0.6.x to 0.7.x:

  https://github.com/zzzeek/alembic/commit/5c747a068b539cec9dd88836427f57352f3f0735

which has this comment:

> The "multiple heads / branches" feature has now landed. This is
by far the most significant change Alembic has seen since its inception;
while the workflow of most commands hasn't changed, and the format
of version files and the ``alembic_version`` table are unchanged as well,
a new suite of features opens up in the case where multiple version
files refer to the same parent, or to the "base".  Merging of
branches, operating across distinct named heads, and multiple
independent bases are now all supported.   The feature incurs radical
changes to the internals of versioning and traversal, and should be
treated as "beta mode" for the next several subsequent releases
within 0.7.
fixes #167

Alembic is installed via the setup.py file:

    install_requires = [
        'alembic',  # XXX I need Alembic, but not Mako or MarkupSafe.

which I guess should specify 0.6.7 or some tested version....

**Comment by lilydjwg** [comment]
I've got into this too :-( I've commented out that line and it seems to work.

**Comment by crusaderky** [comment]
Same problem here on Ubuntu 14.04. pcdummy's patch fixes it for me!

**Comment by tux3** [comment]
I'm also affected by this bug.

**Comment by Burnfaker** [comment]
can be closed...

**Comment by lpirl** [comment]
@Burnfaker: why you think this can be closed? It is still broken in the repository, isn't it?

I think this "fix" just works because the database does not actually get migrated unless you have an existing database from an older version of bedup that used another schema.
It probably ends in some kind of SQL error if old databases do not get migrated properly.

Further, the use of private methods is not advisable anyways.

I'd vote for disabling migrations completely and raising a meaningful error if a migration would actually be done (like "It seems like you updated from an earlier version of bedup. The database must be migrated but this is not implemented yet. Please drop your database file at '/where/it/is.sqlite'") until this is fixed properly.

**Comment by Fry-kun** [comment]
Seeing this issue on a fresh install

**Comment by g2p** [comment]
Fixed now, sorry.

techman83 had it, keeping a version in the db is just future proofing, as all updates to the schema so far were done by adding tables.
